name: build cronet
 
on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'enable ssh debug'     
        required: false
        default: false
      release_tag:
        required: false

jobs:
  build:
    strategy:
      matrix:
        # windows-latest会始终保持最新（目前是2022）
        # windows server 2019安装的是vs2019，windows server 2016安装的是vs2017
        # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
        include: [
          {os: macos-10.15},
          {os: ubuntu-20.04},
          {os: windows-2022},
        ]

    runs-on: ${{ matrix.os }}
    
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      # Enable tmate debugging of manually-triggered workflows if the input option was provided
      - name: setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled == 'true' }}

      - name: build on windows
        if: runner.os == 'Windows'
        run: |
          chmod +x ./build.sh && ./build.sh
        shell: bash
      
      - name: build on mac
        if: runner.os == 'macOS'
        run: |
          chmod +x ./build.sh && ./build.sh
        shell: bash

      - name: build on linux
        if: runner.os == 'Linux'
        run: |
          chmod +x ./build.sh && ./build.sh
        shell: bash